# Generated by Django 4.2.3 on 2023-08-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_address_author_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='citiy',
            new_name='city',
        ),
    ]
